# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту pavelchupin94@yandex.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -pavelchupin94@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

    env:
      global:
        - CODECOV_TOKEN="ffaf3435-6843-4070-ba5d-4eb8bfff72c7"